name: qiskit-metal
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - addict
  - descartes
  - gdspy>=1.5.2
  - geopandas
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pint
  - pyepr-quantum>=0.8.5.7
  - pygments
  - pyside2
  - qdarkstyle
  - qutip
  - scipy
  - shapely
  - jupyter
  - scqubits
  - pip
  - pip:
      - pyaedt
      - gmsh
